import { type NextPage } from 'next'
import Head from 'next/head'

import { api } from '../utils/api'

const Home: NextPage = () => {
    const { data: relayListData } = api.relay.list.useQuery()

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name='description' content='Generated by create-t3-app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main
                className='flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]'>
                <div className='container flex flex-col items-center justify-center gap-12 px-4 py-16 '>
                    <h1 className='text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]'>
                        Create <span className='text-[hsl(280,100%,70%)]'>T3</span> App
                    </h1>
                    <div className='grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8'>
                        {relayListData?.relayList.map((relay) => {
                            return (
                                <div key={relay.id}
                                     className='flex flex-col items-center justify-center gap-4 p-4 bg-white rounded-lg shadow-lg'>
                                    <h2 className='text-2xl font-bold tracking-tight text-gray-800'>{relay.url}</h2>
                                    <p className='text-gray-500'>{relay.id}</p>
                                </div>
                            )
                        })}
                    </div>
                </div>
            </main>
        </>
    )
}

export default Home
